version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  server:
    build: .
    container_name: TaskMaster_server
    ports:
      - "4000:4000"
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run start:dev"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    working_dir: /TaskMaster_Server/src
    depends_on:
      - db

volumes:
  postgres-data: